@base_url = http://localhost:5000/api/auth

### SIGNUP

POST {{base_url}}/signup
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="fullName"

Kürşat Polatci
--boundary123
Content-Disposition: form-data; name="email"

polatcikursat58@gmail.commm
--boundary123
Content-Disposition: form-data; name="username"

kursatpolatciii
--boundary123
Content-Disposition: form-data; name="password"

123456
--boundary123--

### LOGIN

POST {{base_url}}/login
Content-Type: application/json

{
    "email": "polatcikursat58@gmail.com",
    "password": "123456"
}

### LOGOUT

GET {{base_url}}/logout

### CHECK AUTH

GET {{base_url}}/check-auth