@base_url = http://localhost:5000/api/auth

### SIGNUP

POST {{base_url}}/signup
Content-Type: multipart/form-data; boundary=boundary123
Accept-Language: tr

--boundary123
Content-Disposition: form-data; name="fullName"

Kürşat Polatci
--boundary123
Content-Disposition: form-data; name="email"

polatcikursat58@gmail.com
--boundary123
Content-Disposition: form-data; name="username"

kursatpolatci
--boundary123
Content-Disposition: form-data; name="password"

123456
--boundary123--

### LOGIN

POST {{base_url}}/login
Content-Type: application/json
Accept-Language: tr

{
    "email": "polatcikursat58@gmail.com",
    "password": "123456"
}

### LOGOUT

GET {{base_url}}/logout
Accept-Language: tr

### CHECK AUTH

GET {{base_url}}/check-auth
Accept-Language: tr