@base_url = http://localhost:5000/api/expense

### CREATE EXPENSE

POST {{base_url}}/create
Content-Type: application/json
Accept-Language: tr

{
    "title": "Kahve",
    "category": "Yemek",
    "emoji": "☕️",
    "amount": "170",
    "currency": "TRY",
    "date": "2025-04-13"
}

### GET MONTHLY EXPENSES

GET {{base_url}}/get-monthly-expenses
Accept-Language: en

### UPDATE EXPENSE

PUT {{base_url}}/update/67fd09bc49ee836fba7c698d
Content-Type: application/json
Accept-Language: tr

{
    "currency": "USD",
    "emoji": "📦",
    "amount": "32"
}

### DELETE EXPENSE

DELETE {{base_url}}/delete/67fd28a146c2201c3dcea576